language: java
sudo: true
install: true
before_script:
  - echo "MAVEN_OPTS='-Xms512m -Xmx1024m -XX:PermSize=512m -XX:MaxPermSize=1024m'" > ~/.mavenrc
script:
  - mvn clean
  - mvn install -Dmaven.javadoc.skip=true -B -V -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -Dorg.slf4j.simpleLogger.defaultLogLevel=off
jdk:
    - oraclejdk7
